feat: update `d.ts`
graphql/graphql-js pull request #2985
Opened 2021-03-24 03:42 UTC by saihaj

- feat: switch to use ObjMap utiilty type
- feat: convert to use ReadOnlyObjMap and ReadOnlyObjMapLike utilites
- feat: switch to Record utility type
- feat: remove unexported type
- feat: exported type should be readonly
- feat: add types for internal Parser class
- feat: add get Symbol.toStringTag
- feat: add internal annotations
- refactor: no need to code in `d.ts` can just export type
- feat: return AsyncGenerator

2021-03-24 04:01 UTC, saihaj commented
@IvanGoncharov as per #2860 we are dropping support for Typescript v3.7 so that is the only integration test that is failing.

2021-03-31 10:40 UTC, IvanGoncharov requested changes

2021-03-31 10:40 UTC, IvanGoncharov commented on tsconfig.json
> +    "lib": ["es2019", "es2020.string"],
No, keep this as is.
Not all code published as an NPM package and nothing preventing us from using these types there.

2021-03-31 10:43 UTC, IvanGoncharov commented
@saihaj Can you please extract the `AsyncGenerator` change into separate PR?

2021-05-25 01:40 UTC, closed without merging