feat: disable 'did you mean x' during validation
graphql/graphql-js pull request #3467
Opened 2022-01-28 08:15 UTC by n1ru4l

This PR introduces a new property `didYouMean` on the `ValidationContext`, that can be used by validation rules for determining whether suggestions should be added to the error message.

I did not add the test yet as I first want to start the discussion on whether this is how this should be implemented.

______

Related issues:

- https://github.com/graphql/graphql-js/issues/2247
- https://github.com/redwoodjs/redwood/issues/4275

2022-01-28 12:29 UTC, yaacovCR commented
I think this is great!

would suggest option name to be enableSuggestions with default of true, perhaps might eventually default to false

see https://github.com/graphql/graphql-js/issues/2247

in that issue, consensus seems to be around disabling introspection to be one and the same with disabling suggestions, but I think this PR might be about the lower level building blocks that allow that direction

2022-01-28 12:30 UTC, yaacovCR commented
There are also some didYouMean calls in enum parseLiteral, I think we can add an execution option in parallel to the one till validate that then has to be passed to parseLiterals?

2022-01-28 12:35 UTC, n1ru4l commented
> There are also some didYouMean calls in enum parseLiteral, I think we can add an execution option in parallel to the one till validate that then has to be passed to parseLiterals?

I only focused on the validation rules for now. I am happy to also add this to further parts that require it, once there is a consensus on how we should tackle this!

2022-01-28 12:49 UTC, saihaj reviewed
Looks like right way forward to me. 
Side note: we should make validate also take one argument which is an object.

2022-01-28 13:01 UTC, n1ru4l commented
> Side note: we should make validate also take one argument which is an object.

I had a discussion with @benjie about this before in the context of adding `contextValue` to validation rules. One takeaway was "The currently validate signature is useful for the cache use case, [...]". Please correct me if I interpreted this wrong.

````ts
validate(a, b, c)
````

is easier cachable than

```ts
validate({
  a,
  b,
  c,
})
```

For internal reference: https://tortilla-hq.slack.com/archives/CAY2119MX/p1637243621148400

Though I am not against changing the function signature, however, this might be out of the scope of this PR.

2022-02-03 09:02 UTC, benjie commented
I meant that if your validation result is valid independent of context and variables then you can cache the validation result and the next time you see the query you can know it's valid independent of the _new_ context and variables that it comes along with. The actual signature of the function is unimportant so long as context and variables are not included (caching it based on the list of args vs the extracted list of properties isn't much different).

2022-02-03 09:04 UTC, benjie commented
(Also the GraphQL spec itself makes it very clear that validation does not factor in context or variables - anything that does require that (e.g. coercing the variable values) is done during ExecuteRequest.)

2022-02-06 07:48 UTC, dotansimha approved these changes

2022-02-07 14:20 UTC, saihaj approved these changes

2022-05-16 18:51 UTC, IvanGoncharov requested changes
I fully agree wit Lee's coment here: https://github.com/graphql/graphql-js/issues/2247#issuecomment-815430294

It should be configured by schema and should disable the execution of introspection and even access to introspection types from `GraphQLSchema`.
Also, there are other places using `didYouMean` outside of validation, e.g. https://github.com/graphql/graphql-js/blob/e3aaab0e1172136321cce492ccf9b0bbdf10aebe/src/utilities/coerceInputValue.ts#L140

So it should be a solution that can disable introspection leaking all over the library, not only for validation.

2022-12-18 19:30 UTC, PabloSzx approved these changes

2024-08-07 15:40 UTC, andrewmcgivery commented
Are there any plans to complete this PR or is this one stale at this point and would need to start over?

2024-10-13 15:35 UTC, JoviDeCroock commented
Implemented in https://github.com/graphql/graphql-js/pull/4214

2024-10-13 15:35 UTC, closed without merging