Fix crash in node when mixing sync/async resolvers (backport of #3529)
graphql/graphql-js pull request #3573
Opened 2022-05-11 15:22 UTC by chrskrchr

This is a backport of #3529 from the `16.x` release line to `15.x`.  

Full credit to @asztal for identifying the fix and submitting the original PR.

2022-05-11 15:29 UTC, chrskrchr commented on src/__testUtils__/expectJSON.js
> +import { expect } from 'chai';
Backported and stripped type information from this module on `main`:

https://github.com/graphql/graphql-js/blob/main/src/__testUtils__/expectJSON.ts

2022-05-11 15:53 UTC, chrskrchr commented
Moving this PR back to draft while I sort out the typing issues.

2022-05-11 16:36 UTC, IvanGoncharov requested changes
Also please backport it to v16.
It would be strange to have this fix in v15 and v17 but not v16 :)

2022-05-11 18:05 UTC, chrskrchr commented
> Also please backport it to v16. It would be strange to have this fix in v15 and v17 but not v16 :)

Thanks for the heads up!  I wasn't aware that `main` had moved on to v17.  Submitted a similar PR for `16.x.x` here:

https://github.com/graphql/graphql-js/pull/3576

2022-05-20 14:36 UTC, chrskrchr commented
@IvanGoncharov - I finally worked through the EasyCLA issues, would you mind taking another look at this PR?

2022-08-18 16:41 UTC, chrskrchr commented
Closing this and re-submitting as a new PR per the guidance in #3651.

2022-08-18 16:41 UTC, closed without merging