use named parameters for node visit context info
graphql/graphql-js pull request #3619
Opened 2022-05-31 03:03 UTC by yaacovCR

2022-05-31 03:19 UTC, yaacovCR commented
Motivation:

1. Some visit context information is rarely used, this could be pathway toward refactoring, future-proofing any breaking changes to come. (see: https://github.com/graphql/graphql-js/issues/3225)
2. Eventually, BREAK and/or other visit controllers could be added as third argument directly to the visitor method rarely than exported from the library. (see https://github.com/graphql/graphql-js/pull/3616)

2022-05-31 05:01 UTC, saihaj approved these changes

2022-06-06 12:39 UTC, IvanGoncharov requested changes
@yaacovCR I'm totally for this change 👍 
But it makes a breaking change without migration path and means you can't support v16 and v17 in the same code base.
Are we sure we want to do this?

2022-06-07 16:50 UTC, yaacovCR commented
Backwards compatible version is easier said than done. We can't just change the second argument to keyOrContext, because the directionality is actually opposite, our users are supplying the function, rather than us writing it. How would we know which type of function we were supplied and whether to pass the key or the context?

What seems possible, but not necessarily the best choice: we could make our users specify in some way which type of visitor function they are passing, and then require them to pass it that way. Easiest but ugliest, we could create an entire new function called `visitWithNamedVisitorFnArguments` that supercedes `visit` and then deprecate `visit`.

Adding to next js-wg. If you are reading this, please feel free to chime in.

2026-02-15 15:03 UTC, yaacovCR commented
closing this old, stale PR, still available for reference if seems of greater utility.

2026-02-15 15:03 UTC, closed without merging