fix GraphQLWrappingType
graphql/graphql-js pull request #3622
Opened 2022-05-31 12:32 UTC by yaacovCR

GraphQLNonNull wrapper can only be applies to nullable types

related: #3597
see also: https://github.com/graphql/graphql-js/pull/3617#discussion_r885544662

2022-05-31 12:36 UTC, n1ru4l approved these changes

2022-06-01 04:51 UTC, saihaj approved these changes

2022-06-01 09:47 UTC, IvanGoncharov requested changes
Looks good!

But as previously discussed you need to provide a description of your change, currently, it only contains links.

Also, bug fixes should include tests, otherwise, we have no way to detect regressions.

2022-06-01 11:37 UTC, yaacovCR commented
We all can and do make mistakes, especially when busy. An extra note explicitly stating that this was a long standing bug could not have hurt, sure.

2022-06-01 18:45 UTC, yaacovCR commented
I updated the description above. For good measure, I did a quick search for additional code points to correct and udpated the title of this PR.

2022-06-06 02:22 UTC, dotansimha approved these changes

2022-06-06 02:27 UTC, dotansimha commented
@IvanGoncharov Any chance you can review this PR again? 
At the moment, we don't have TypeScript types testing setup at the moment, and from my experience with codegen and other libraries, it is not always easy to add TypeScript types testing. 
Do you think we can merge this one and maybe open an issue to improve TS types testing later? (also because this PR is fairly small and simple, and it's really addressing a real TS types bug)

2022-06-06 12:25 UTC, IvanGoncharov commented
> At the moment, we don't have TypeScript types testing setup, and from my experience with codegen and other libraries, it is not always easy to add TypeScript types testing.
Do you think we can merge this one and maybe open an issue to improve TS types testing later? (also because this PR is fairly small and simple, and it's really addressing a real TS types bug)

Agree, answered here https://github.com/graphql/graphql-js/pull/3622#issuecomment-1143484274

2022-06-06 12:25 UTC, merged

2023-04-11 21:06 UTC, Simpdaddyjosh approved these changes